# name: App health check

# on:
#   schedule:
#     - cron: "* 12 * * *"

# jobs:
#   url_health_check:
#     name: Check deployed app
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: jtalk/url-health-check-action@v3
#         with:
#           url: https://red-thunder-8099.fly.dev/
